name: Build Tweak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install ldid make

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Install iOS SDK
        run: |
          mkdir -p $HOME/theos/sdks
          cd $HOME/theos/sdks
          curl -L -o sdk.tar.xz https://github.com/theos/sdks/releases/download/master-146e41f/iPhoneOS12.4.sdk.tar.xz
          file sdk.tar.xz
          tar -xf sdk.tar.xz
          ls

      - name: Build Package
        run: |
          export THEOS=$HOME/theos
          make clean
          make package FINALPACKAGE=1

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: deb-file
          path: packages/*.deb
