name: Build Tweak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install ldid make

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Install iOS SDK
        run: |
          mkdir -p ~/theos/sdks
          cd ~/theos/sdks
          curl -L -o sdk.tar.xz https://github.com/theos/sdks/releases/download/master-146e41f/iPhoneOS12.4.sdk.tar.xz
          tar -xf sdk.tar.xz

          # Fix old SDK module map error on new macOS/clang
          if [ -f ~/theos/sdks/iPhoneOS12.4.sdk/usr/include/mach-o/module.map ]; then
            mv ~/theos/sdks/iPhoneOS12.4.sdk/usr/include/mach-o/module.map ~/theos/sdks/iPhoneOS12.4.sdk/usr/include/mach-o/module.modulemap
          fi

      - name: Build Package
        run: |
          export THEOS=$HOME/theos
          make clean
          make package FINALPACKAGE=1

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: appstoretroller-deb
          path: packages/*.deb
